### ISSUE TITLE
Rich text integration

### ISSUE THREAD

**Issue by RochetS** [ObeoNetwork/M2Doc#303] opened 2018-09-10 14:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When generating a document from Capella, rich text fields are generated as strings. Format is not interpreted and the tags are kept as they are.

## Expected behavior

Provide an option to reuse existing text format in the source model.

<pre><code>
M2Doc version: 2.0.0
Capella version: 1.2.1

**Comment by ylussaud** [comment] 2018-09-21 14:53
This issue is related to #265

**Comment by ylussaud** [comment] 2019-10-29 08:44
The format is defined using HTML. So this ticket is a duplicate of #265

**Closed by ylussaud** 2019-10-29 08:44 UTC
Labels: feature
