### ISSUE TITLE
Figures inserted inside a template construct have incorrect index and are not picked up by the table of figures

### ISSUE THREAD

**Issue by flatombe** [ObeoNetwork/M2Doc#443] opened 2021-09-13 15:05 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

When a Word figure is inserted thanks to a template construct (`m:template`), its index is not correct (several figures end up with the same index) and it is not being picked up by the table of figures (neither with option "updateFields" in the configuration nor with a manual update of the table of figures).
Current workaround is to, unfortunately, inline the contents of the template construct.

## Expected behavior

Contents inserted thanks to a template construct should not be different from if they were inlined.
If it should, then the documentation should mention it.

## Environment

<pre><code>
M2Doc version: 3.2.0.202105181517
Eclipse version: Capella 1.4.1.202006301603
Platform version:  Windows 10

Others:

</code></pre>

**Comment by ylussaud** [comment] 2024-09-04 08:52
This is a duplicate of issue #412.

**Closed by ylussaud** 2024-09-04 08:52 UTC
