### ISSUE TITLE
The new generation wizard should create an empty template

### ISSUE THREAD

**Issue by juliendupont** [ObeoNetwork/M2Doc#328] opened 2019-02-13 09:12 UTC
The new generation wizard should create an empty template if it doen't exist.

**Comment by ylussaud** [comment] 2019-10-17 09:23
It's not possible in the new generation wizard since we are using the existing template to initialize the genconf model. But I can adapt the new project wizard (see #335) to create a new template.

**Comment by ylussaud** [comment] 2019-10-29 14:16
This is a duplicate of #319.

**Closed by ylussaud** 2019-10-29 14:16 UTC
Labels: enhancement, feature
