### ISSUE TITLE
IOException with asImage() on a sirius diagram with invalid characters in its name

### ISSUE THREAD

**Issue by sthibaudeau** [ObeoNetwork/M2Doc#281] opened 2018-02-09 10:31 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

IOException thrown when exporting a sirius diagram with asImage() if the representation name contains invalid characters (as carriage return in my case).
A temporary file is created using the sirius diagram's name and invalid characters lead to an IOException and an error in the generated file.

Example : asImageByRepresentationDescriptionName(org.eclipse.emf.ecore.EObject,java.lang.String) with arguments [Task[TRANSIENT], Actions Plan] failed:  La syntaxe du nom de fichier, de répertoire ou de volume est incorrecte

## Expected behavior

The name used for the temporary file should be sanitized to avoid IOException.

## Minimal reproduction of the problem with instructions

Insert characters that are invalid for a filename into a diagram name then try to export as image in a template.

## Environment

<pre><code>
M2Doc version: 0.11.0
Eclipse version: Neon
Platform version:   Windows 10

Others:

</code></pre>

**Comment by ylussaud** [comment] 2018-03-13 15:01
This is a duplicate of bug #270. It is fixed in version 1.1.0.

**Closed by ylussaud** 2018-03-13 15:01 UTC
