### ISSUE TITLE
Add PDF support

### ISSUE THREAD

**Issue by ejuliot** [ObeoNetwork/M2Doc#403] opened 2020-12-14 07:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

Some users are requesting PDF export from models. M2Doc only support DOCX and so users have to do a manual translation after generation or to create a specific code to automatise the translation.

## Expected behavior

To have a built-in option to generate a PDF file. It should be avoid by M2Doc API and directly in the UI. The ideal would be to let the user choose to generate both DOCX and PDF, just DOCX, just PDF.
POI already has a built-in support for DOCX to PDF conversion. Loot at https://stackoverflow.com/questions/43363624/converting-docx-into-pdf-in-java  (org.apache.poi.xwpf.converter.pdf.PdfConverter)

**Comment by ylussaud** [comment] 2020-12-14 08:12
This is a duplicate of #357.

**Closed by ylussaud** 2020-12-14 08:12 UTC
