### ISSUE TITLE
Useless emptu line systematically inserted before bullet lists coming from Capella descriptions

### ISSUE THREAD

**Issue by bsphane** [ObeoNetwork/M2Doc#455] opened 2022-01-11 12:54 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior

An empty line is inserted before the first bullet when publishing Capella descriptions containing bullet lists. 

## Expected behavior

No extra line is inserted. 

## Minimal reproduction of the problem with instructions

The following source code can be used:

```
<div>Preceding sentence
<blockquote>
<div>
<ul>
               <li>bullet 1</li>
</ul>
<blockquote>
<div>
<ul>
               <li>bullet 1.1</li>
               <li>bullet 1.2</li>
</ul>
</div>
</blockquote>
```

## Environment

<pre><code>
M2Doc version: 3.2.1

Others:

</code></pre>

**Comment by ylussaud** [comment] 2024-08-27 09:06
This issue seems fixed on master probably with improvement of previous minor versions of M2Doc. If the issue is still here please reopen this issue and attach a template that can reproduce this issue.

**Closed by ylussaud** 2024-08-27 09:06 UTC
