### ISSUE TITLE
Problems in generated docx

### ISSUE THREAD

**Issue by phdesanois** [ObeoNetwork/M2Doc#373] opened 2019-12-06 13:28 UTC
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please have a look to the support pages of our website : http://m2doc.org/support/
</code></pre>

## Current behavior
Generate a document with 200 diagrams.
Open Word , the following message is dispalyed :
"Impossible d'ouvrir le fichier xxxx.docx. Des problèmes ont été décelés dans son contenu."
Word proposes to repair the document, accept.
The document can be opened.

The analysis of the generated document shows that in the files
word / document.xml and word / footer1.xml
there is the same <wp: docPr id = "49">

the <wp:docPr id="49"> in word/footer1.xml is present in the template.

## Expected behavior
During generation M2doc must check that new id doesn't exist in the template.

## Minimal reproduction of the problem with instructions
See current behavior

## What is the motivation / use case for changing the behavior?
For customer, this message generate questions on the document quality.
It is not needed to repair and save the document

## Environment

<pre><code>
M2Doc version: 2.0.3
Obeo version : 11.1.2
Eclipse version: X.Y.Z
Platform version:   Windows  7

Others:

</code></pre>

**Comment by ylussaud** [comment] 2019-12-06 13:42
Do you have a reproduction case ? The minimal template to reproduce would be nice. Or at least can you describe what is the content of your header ?

**Comment by phdesanois** [comment] 2019-12-06 15:10
[pb_m2doc.zip](https://github.com/ObeoNetwork/M2Doc/files/3932756/pb_m2doc.zip)
You can find in this zip file a simple project with, ecore model, genconf, template, and the generated file  with this problem.
Thanks.

**Comment by ylussaud** [comment] 2019-12-06 15:25
thank you I'll have a look.

**Comment by ylussaud** [comment] 2019-12-09 13:37
I didn't reproduce with the master branch. It's possible that bug has already been fixed.
Can you test with the [nightly update site](https://s3-eu-west-1.amazonaws.com/obeo-m2doc-releases/master/nightly/repository) ? Just to make sure this is fixed.

**Comment by phdesanois** [comment] 2019-12-09 18:12
I reproduce the problem with the nightly version to day.
My word version is 14.0.7237.5000 (32 bits)

Did you open the generated document that I provided in the zip file ? Is there the problem ?

**Comment by ylussaud** [comment] 2019-12-10 08:26
Yes I opened it, and the problem is present. I'll try to generate again... I had to change the .aird file.

**Comment by ylussaud** [comment] 2019-12-17 10:09
I reproduced the problem. There is an anchor to a text area or form in the section two footer. I removed it and the document can be opened by MS Word.
see the modified [templateModel.docx](https://github.com/ObeoNetwork/M2Doc/files/3972634/templateModel.docx).

**Comment by ylussaud** [comment] 2019-12-18 13:14
Aside of the problem of the version variable that was not recognized (this is fixed by the commit above). Is your problem solved with the modified template ?
I'm about to release nad need to close this issue...

**Comment by phdesanois** [comment] 2019-12-18 13:37
Yes, the problem is solved.
Thanck you

**Comment by ylussaud** [comment] 2019-12-18 13:52
ok

**Closed by ylussaud** 2019-12-18 13:52 UTC
