### ISSUE TITLE
Tables in reqursive templates

### ISSUE THREAD

**Issue by dsryzhov** [ObeoNetwork/M2Doc#350] opened 2019-06-05 18:33 UTC
When sub-tempates are called reqursively tables are placed in the wrong place.
In the attached test two templates are defined.

One tempate is adding table into document.
Second template is calling first template.

In the first test first template is called for all data packages.
In the second test second template is called fo all data packages.

For the second test table placement is wrong. At first table is placed in document. And after it the package heading is placed.
[DiagramTest.docx](https://github.com/ObeoNetwork/M2Doc/files/3258552/DiagramTest.docx)
[DiagramTestTemplate.docx](https://github.com/ObeoNetwork/M2Doc/files/3258553/DiagramTestTemplate.docx)

**Comment by dsryzhov** [comment] 2019-06-05 18:42
I've been using reqursive templates to generate hierarchical sections from model. Some times all tables from different levels are stacked in the beginning of the document

**Comment by dsryzhov** [comment] 2019-06-05 18:44
As a workaround I've started to use one level sub-templates called from hierarchical {m:for} in the main template.

**Comment by ylussaud** [comment] 2019-06-06 07:11
This is a duplicate of bug #341.

**Closed by ylussaud** 2019-06-06 07:11 UTC
